version: '2'

services:
  db_publicnews:
    container_name: postgres_publicnews
    image: postgres:alpine
    restart: always

  web_publicnews:
    container_name: web_publicnews
    build: ./publicNews
    command: sh /code/run.sh
    volumes:
      - ./publicNews:/code
      - /var/www/public/static/:/var/www/public/static/
      - ./publicNews/media/:/code/media/

    depends_on:
      - db_publicnews

  nginx_publicnews:
    container_name: nginx_publicnews
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - /var/www/public/static/:/var/www/public/static/
      - ./publicNews/media/:/code/media/
      
    depends_on:
      - web_publicnews
