version: '2'

services:
  db_publicnews:
    container_name: postgres_publicnews
    image: postgres
    restart: always

web_publicnews:
    build: ./publicnews
    command: sh /code/run.sh
    volumes:
      - ./publicnews:/code
      - /var/www/static/:/var/www/static/
      - /var/www/files/:/var/www/files/

    depends_on:
      - db_publicnews

  nginx_publicnews:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - /var/www/static/:/var/www/static/
        - /var/www/files/:/var/www/files/
        - ./nginx/:/etc/nginx/conf.d/
      depends_on:
        - web_publicnews
