# Generated by Django 2.0.6 on 2018-08-01 08:01

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspublic',
            name='content',
            field=app.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
