# Generated by Django 2.0.7 on 2018-08-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180802_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspublic',
            name='file',
        ),
        migrations.RemoveField(
            model_name='newspublic',
            name='url',
        ),
    ]
