# Generated by Django 2.0.7 on 2018-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180803_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspublic',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
