# Generated by Django 2.0.7 on 2018-09-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstype',
            old_name='news',
            new_name='newspublic',
        ),
    ]
