# Generated by Django 2.0.7 on 2018-09-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180903_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstype',
            old_name='newstype',
            new_name='newstyp',
        ),
    ]
