# Generated by Django 2.0.7 on 2018-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180910_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspublic',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
