# Generated by Django 2.0.7 on 2018-09-10 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180910_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspublic',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
